spring:
  http:
    encoding:
      charset: UTF-8
server:
  port: 443
  http:
    port: 8080
  ssl:
    key-store: classpath:ssh.keystore
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat